# Generated by Django 2.2 on 2019-04-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('price', models.SmallIntegerField()),
                ('score', models.CharField(choices=[(1, 'low'), (2, 'low'), (3, 'low'), (4, 'middle'), (5, 'middle'), (6, 'middle'), (7, 'middle'), (8, 'high'), (9, 'high'), (10, 'high')], max_length=10)),
            ],
        ),
    ]
