# Generated by Django 2.2 on 2019-04-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20190410_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.CharField(choices=[('low', '1'), ('low', '2'), ('low', '3'), ('middle', '4'), ('middle', '5'), ('middle', '6'), ('middle', '7'), ('high', '8'), ('high', '9'), ('high', '10')], max_length=1),
        ),
    ]
