# Generated by Django 2.2 on 2019-04-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_auto_20190410_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.CharField(choices=[('low', '1'), ('low', '2'), ('low', '3'), ('middle', '4'), ('5', 'middle'), ('middle', '6'), ('middle', '7'), ('high', '8'), ('high', '9'), ('high', '10')], default='5', max_length=100),
        ),
    ]
