# Generated by Django 2.2 on 2019-04-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_auto_20190410_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.CharField(choices=[('1점', '1'), ('2점', '2'), ('3점', '3'), ('4점', '4'), ('5점', '5'), ('6점', '6'), ('7점', '7'), ('8점', '8'), ('9점', '9'), ('10점', '10')], default='5', max_length=100),
        ),
    ]
